---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  template:
    spec:
      containers:
      - name: website
        imagePullPolicy: Always
        image: nginx:latest
        env:
        - name: variable1
          value: "hello"
        - name: variable2
          value: "hello"

        resources:
          limits:
            cpu: 100m
