apiVersion: v1
kind: Service
metadata:
  labels:
    svc: website
  name: website-master
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: metric
    port: 9000
    protocol: TCP
  selector:
    tier: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: website
  name: website-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: website
  template:
    metadata:
      labels:
        tier: website
    spec:
      containers:
      - env:
        - name: variable1
          value: hello
        - name: variable2
          value: hello
        image: nginx:latest
        imagePullPolicy: Always
        name: website
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 100m
      imagePullSecrets:
      - name: image-registry-secret
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website-master
  namespace: default
spec:
  rules:
  - host: kavoyo.com
    http:
      paths:
      - backend:
          serviceName: website-master
          servicePort: 80
        path: /
